---
- hosts: k8cluster
  become: True
  pre_tasks:
    - name: Download container-selinux rpm
      yum:
        name: http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.99-1.el7_6.noarch.rpm
        state: present
        update_cache: yes
  roles: 
    - geerlingguy.docker
    - geerlingguy.kubernetes
